language: go
install: make deps test
go:
  - 1.2
  - 1.3
  - tip
before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y libsnappy-dev autoconf automake
  - git clone https://github.com/spotify/sparkey.git
  - "(cd sparkey && autoreconf --install && ./configure && make && sudo make install && sudo ldconfig)"
